### ISSUE TITLE
Timestamp only

### ISSUE THREAD

**Issue by Kyoyashi** [jasmaa/niconico-yt#1]
I happend to see lots of video witch have timestamped comments. Would it be possible to ad an option for showing only those, and at the correct time?
Note that some user tend to post one single comment with multiple timestamp, so a single comment should be broken down into single sub-comment in that case (I suppose you can simply use the line-break or the dot).

**Comment by jasmaa** [comment]
Can you give an example of what you mean?

Unfortunately, it doesn't look like [Youtube's list comment API](https://developers.google.com/youtube/v3/docs/comments/list) supports any sort of time range querying. It also doesn't look like the [comment model](https://developers.google.com/youtube/v3/docs/comments#resource) keeps track of how far viewer was in the video when the comment was left, so it may not be possible to fully replicate Nico Nico Douga's real-time comment system here.

**Comment by Kyoyashi** [comment]
I was thinking about a simpler code, something that just looks for [0-9]:[0-9][0-9] in any comment/line, and then displays that comment/line around that time.

**Comment by jasmaa** [comment]
Thanks for the suggestion! (I like this a lot more than what I originally had actually)

I've changed this to be the default behavior in [v2.0.0](https://github.com/jasmaa/niconico-yt/releases/tag/v2.0.0). Going to close this.
